### ISSUE TITLE
Request to Remove SimpleLogin domains from your Temporary Emails list

### ISSUE THREAD

**Issue by Nikola-Test-for-Proton** [bnkas/lists#1]
Hi, this is Nikola.

I work in Proton's (and SimpleLogin's) Anti-Abuse team and noticed that some of our domains are present your list of temporary emails. To be more precise, 8shield.net, 8alias.com, simplelogin.com, simplelogin.fr, and slmail.me, are included.

At Proton, we take anti-abuse especially seriously and would like to work with you on having the abovementioned domains removed from your list. Can you elaborate why these domains have been incorporated? Would it be possible to correct this?

We would appreciate it if you could look into this for us accordingly.

Your patience and understanding are greatly appreciated.

Have a pleasant day.

**Comment by bnkas** [comment]
Hi @Nikola-Test-for-Proton, 

Thank you for reaching out. This list is for private use and is available for anyone that wishes to block temporary email addresses. I am certain your service takes reported email abuse seriously when it comes to spam, phishing, etc; however, there is another type of abuse (or misuse) of your service by some users that often goes unaddressed; for example, bypassing free trial restrictions/limits, creating and abandoning accounts resulting in bounced emails, etc. Such abuse/misuse can be more easily addressed with typical email providers; for example, large email providers have limits on aliases or patterns to identify them and users go through different layers of verification so it is less likely for this legitimate user to abuse an online service limit or to haphazardly create and abandon accounts within hours resulting in bounced emails.

These are not theories based on assumptions, but unfortunate facts on based on real-world behavior for users with email domains on the list, including your service. 

Thanks.

**Comment by Nikola-Test-for-Proton** [comment]
Hello,

Thank you for following up. 

I'm sorry that I missed your response. 

Please note that I understand the point you're making, but don't believe that what you've written up is an accurate representation of how we go about things on our end - we have systems and machine learning models in place that work to prevent Registration Abuse, Spam, Phishing, and the like, on our platforms. 

Also, we do have a limit on how many aliases you can create with a Free account. Users with a paid SL subscription can create as many as they'd like, but we have a strict limit on only using 1 alias on just 1 third-party platform. 

If you can provide me with concrete examples, I'd be happy to look at things for you.

Feel free to DM me or reach out at antiabuse@proton.me. 

Have a pleasant day.
